### ISSUE TITLE
This package doesn't works if included as package

### ISSUE THREAD

**Issue by Reggionick** [dudesuh/react-leaflet-multi-options-polyline#1]

**Comment by dudesuh** [comment]
Hello @Reggionick, what version of react-leaflet are you using? The 2.0.0 version of this package is meant to be used with any version 2 of react-leaflet. If this is not the case, I ask you to describe the error.

**Comment by jounisuo** [comment]
If trying to use as a package I get TypeError: Cannot read property 'addLayer' of undefined
node_modules/react-leaflet-multi-options-polyline/node_modules/react-leaflet/es/MapLayer.js:40





I'd guess the important part here is the path... The error is from the 2.0.1 react-leaflet defined as a dependancy on the package, not the 2.2.1 I' m using on my project.

Copy pasting the component only to my project and importing that instead works.

Maybe change the version to >=2.0.1 < 3.0 on package.json?

**Comment by dudesuh** [comment]
Hello @jounisuo , I made a patch(v2.0.2), where I updated all dependencies and resolved some security vulnerabilities. Can you test with the new version and see if the problem is resolved? Thanks.

**Comment by jounisuo** [comment]
Sorry for the long delay. The problem is resolved.
