### ISSUE TITLE
How to include this component into a React-Leaflet Map using hooks

### ISSUE THREAD

**Issue by rodrigofcaba** [dudesuh/react-leaflet-multi-options-polyline#34]
Hi!

I'm working on a project in which I render a map tracking a flight. I need to draw the route flown by a plane. I already have this implemented in a web version without react using ordinary [ Leaflet MultiOptions Polyline](https://github.com/hgoebl/Leaflet.MultiOptionsPolyline).  However, I am not able to make this work in React. I am using the latest version of [React Leaflet](https://react-leaflet.js.org/). Hence, I am using MapContainer component instead of Map and my components are functional (i.e using React hooks) and not ES6 classes anymore. I cannot find any example of how to use this component within functional components. I cannot find either any documentation about what makes each of the pieces (i.e. "ref", "optionIdxFn", etc.). So, basically I have some questions.

1. Is it possible to include this component in my map using hooks? For example, what is "map" in the example provided in the docs? Is this the same as a ref created with useRef() hook? If that is the case, Can I pass my map using useMap() hook?
2. When it comes to optionIdxFn, how can I pass to this function the data comming from Redux store (I need to push new datapoints to the store in order to update the route)? I have the coordinates (i.e Latlng positions) and the altitude the plane is flying, but can't really figure out how to implement this with hooks. 

Here you have a piece of code with my current implementation. Obviously, it doesn't work because I cannot access route[2] which is the altitude flown by the plane.

```javascript
function Route() {
	const map = useMap();
	const ref = useRef(map);
	const route = useSelector((state: RootState) => state.route);

	const optionIdxFn = (route) => {
		let i;
		const altThresholds = [
			1000, 2500, 5000, 10000, 15000, 20000, 25000, 30000,
		];

		for (i = 0; i < altThresholds.length; ++i) {
			if (route[2] <= altThresholds[i]) {
				return i;
			}
		}
		return altThresholds.length;
	};

	const options = [
		{ color: '#0000FF' },
		{ color: '#0040FF' },
		{ color: '#0080FF' },
		{ color: '#00FFB0' },
		{ color: '#00E000' },
		{ color: '#80FF00' },
		{ color: '#FFFF00' },
		{ color: '#FFC000' },
		{ color: '#FF0000' },
	];

	return (
		<ReactLeafletMultiOptionsPolyline
			ref={ref}
			positions={[route[0], route[1]]}
			weight={5}
			lineCap="butt"
			opacity={0.75}
			smoothFactor={1}
			optionsIdxFn={optionIdxFn}
			options={options}
		/>
	);
}
```

I'm using Redux Toolkit. My slice looks like this:

```javascript
type Route = [number, number, number][];
const initialState: Route = [];

export const routeSlice = createSlice({
	name: 'route',
	initialState,
	reducers: {
		updateRoute: (
			state,
			action: PayloadAction<{ lat: number; lon: number; alt: number }>
		) => {
			const { lat, lon, alt } = action.payload;
			state.push([lat, lon, alt]);
		},
		cleanRoute: () => {
			return initialState;
		},
	},
});

export const { updateRoute, cleanRoute } = routeSlice.actions;

export default routeSlice.reducer;
```

As you can see, it receives the three parameters and updates the state of the application so I have datapoints with lat, lon and altitude. I guess this should be accessible to my Route component in order to render the route flown by the plane and change color according to altitude (which is my final goal).

**Comment by dudesuh** [comment]
Hello Rodrigo,

You couldn't use the **useMap** hook because this library was still in _React 16.11_ as this is a library I no longer use, but I try to maintain it when people need to use it.
I've just released a new version(**3.0.0**) that updates all the dependencies to the last version available, which includes the usage of React hooks and the **useMap** hook from _react-leaflet_. I also deleted some dependencies that weren't being used.

Can you install the last version and see if your use case works?
If you still need some example, you can check the code in [examples/src/index](https://github.com/dudesuh/react-leaflet-multi-options-polyline/blob/master/js/examples/src/index.jsx) and [examples/src/DataMap](https://github.com/dudesuh/react-leaflet-multi-options-polyline/blob/master/js/examples/src/DataMap.jsx).
If even with the update and examples, you can't make your use case to work, let me know so tomorrow I can help you.

**Comment by rodrigofcaba** [comment]
Hi, Ricardo,

Wow, that's fantastic! Thank you so much for the quick reply and the new release. I'll definitely test it and let you know. But looking at the example it will surely work.

Thanks once again!

**Comment by rodrigofcaba** [comment]
Hi Ricardo,

I could give it a try and some things are not working as expected. I can at least implement the component without errors but I cannot pass some of the props, specifically: weight, lineCap, opacity and smothFactor. It looks like those are not considered in Component's props.

Moreover, optionIdxFn prop changed its name from previous **optionsIdxFn** (not big deal, but just in case). Also, this prop seems to be not working properly. Although I passed my own function following the pattern in the example for "altitude", colors are not working. The whole Polyline component is red (regardless of the altitude). In that regard, what is the variable passed to optionIdxFn? Is it an element of the LatLng array, right? If that is the case it should be ok, since I'm checking the third element (altitude).

Just in case I'm doing something wrong, this is my implementation now (the component is rendered inside of my MapContainer component):

```javascript
import 'leaflet/dist/leaflet.css';
import { useSelector } from 'react-redux';
import { RootState } from 'redux/store';
import ReactLeafletMultiOptionsPolyline from './Route';

function Route() {
	const route = useSelector((state: RootState) => state.route);

	const optionIdxFn = (point) => {
		let i;
		const altThresholds = [
			1000, 2500, 5000, 10000, 15000, 20000, 25000, 30000,
		];

		for (i = 0; i < altThresholds.length; ++i) {
			if (point[2] <= altThresholds[i]) {
				return i;
			}
		}
		return altThresholds.length;
	};

	const options = [
		{ color: '#0000FF' },
		{ color: '#0040FF' },
		{ color: '#0080FF' },
		{ color: '#00FFB0' },
		{ color: '#00E000' },
		{ color: '#80FF00' },
		{ color: '#FFFF00' },
		{ color: '#FFC000' },
		{ color: '#FF0000' },
	];

	return (
		<ReactLeafletMultiOptionsPolyline
			positions={route}
			weight={5}
			lineCap="butt"
			opacity={0.75}
			smoothFactor={1}
			optionIdxFn={optionIdxFn}
			options={options}
		/>
	);
}

export default Route;
```

By the way, will you upload the new release as a npm package? It would be much easier for me and my team in the future. 

Thanks in advance! ;)

**Comment by dudesuh** [comment]
Hi again Rodrigo,

Let me answer your question by point:
1. **_NPM Package_** - This is an NPM package, you can do yarn add/npm install react-leaflet-multi-options-polyline;
2. **_Cannot pass some of the props, specifically: weight, lineCap, opacity and smothFactor_** - You can pass Polyline's props as normal props in the **ReactLeafletMultiOptionsPolyline**. The following is the code that creates the lines in the map and as you can see, it passes all the props to Polyline.
```javascript
    return (
        <FeatureGroup>
            {lines.map((optionsLine, optionsIdx) =>
                optionsLine.map((line, idx) => (
                    <Polyline
                        key={idx}
                        {...props}
                        positions={line}
                        {...props.options[optionsIdx]}
                    />
                ))
            )}
        </FeatureGroup>
    );
```
3. **_optionIdxFn name changed_** - It was always optionIdxFn even in the [JS library from hgoebl](https://github.com/hgoebl/Leaflet.MultiOptionsPolyline);
4. **_Colors not working_** - The colors work, the problem can be the values in the threshold array you're using or the colors. I created an example with lower thresholds, using the hochries.json values, and this is the result
![image](https://user-images.githubusercontent.com/17552976/181743276-6f011798-15f8-41d5-a64f-3b29e0dfd8f9.png)
```javascript
function Route() {
	const optionIdxFn = (point) => {
		let i;
		const altThresholds = [
			500, 1000, 1200, 1500, 1800, 2000, 2100, 2200,
		];

		for (i = 0; i < altThresholds.length; ++i) {
			if (point.alt <= altThresholds[i]) {
				return i;
			}
		}
		return altThresholds.length;
	};

	const options = [
		{ color: '#ffba08' },
		{ color: '#a2aebb' },
		{ color: '#3f88c5' },
		{ color: '#d00000' },
		{ color: '#1c3144' },
		{ color: '#4c243b' },
		{ color: '#54457f' },
		{ color: '#fdfffc' },
		{ color: '#011627' },
	];

	return (
		<ReactLeafletMultiOptionsPolyline
            positions={hochries}
			weight={80}
			lineCap="butt"
			opacity={0.75}
			smoothFactor={1}
			optionIdxFn={optionIdxFn}
			options={options}
		/>
	);
}
```

As to why your example is not working, I think it's because of this line `if (point[2] <= altThresholds[i]) {`,  because _point_ will be a Leaflet LatLng object, which contains the fields lat, lng and alt, so the line should be `if (point.alt <= altThresholds[i]) {` 

I also pushed a new version.

**Comment by rodrigofcaba** [comment]
Hi again Ricardo,

Thank you very much for your detailed answer. I downloaded it first using npm, I meant the new release 3.0.0 since I couldn't update the package yesterday using ordinary npm update command. Now I see the new version up and have the 3.0.9 release installed.

I changed my syntax to "point.alt" since I agree it is a Leaflet LatLng object. Now, this is the data I send to the component:

```typescript
interface RouteFeature {
	lat: number;
	lng: number;
	alt: number;
}
interface RouteState extends Array<RouteFeature> {}
```

However, I'm getting an error when trying  to render the map now. It is apparently due to call useState on null in the ReactLeafletMultiOptionsPolyline component:

![image](https://user-images.githubusercontent.com/68204617/181761885-583ea62d-76f9-4d8a-9e35-1e822104353d.png)

I'm not getting any error on the props side now. I can pass the props to the component. But for some reason, the useState hook inside it does not work. I'm doing everything as you do in the example, the only difference is that my data instead of comming from a json file, they come from redux store since I update the state when new data comes from the simulator to which the program is connected (this is a tracker built using electron). I can see the data in the store, I can also access LatLng objects using console.log and I pass these positions to the component but I'm getting the same error referring to the useState hook all the time. 

Interestingly enough, yesterday, using 3.0.0 release from github, I could mount and render the component without some props, but today I cannot even render the Polyline.

I hope you can help me with this and I already appreciate your help a lot. 
Thanks in advance!

**Comment by dudesuh** [comment]
Hi Rodrigo,

It looks like the component can't find react. Try to uninstall and install the latest version of React, or try to import react in the file you're importing the ReactMultiOptionsPolyline. [StackOverflow issue](https://stackoverflow.com/questions/71898427/getting-error-typeerror-cannot-read-properties-of-null-reading-usestate-o)
I found another stackoverflow forum talking about not using async in the component. [StackOverflow issue](https://stackoverflow.com/questions/71904060/uncaught-in-promise-typeerror-cannot-read-properties-of-null-reading-usesta)

Or try to do npm install or yarn, might be some dependency errors.

**Comment by rodrigofcaba** [comment]
Hi again Ricardo,

You are definitely right. I updated some dependencies and now everything is working fine. Thank you so much for your help and your great work.

Shall I close this issue? 

Thanks again and all the best ;)
